#可以通过重载材质包来重载这些功能
options:
  #启动ommc方块模型修复(可能会影响其他模组)(可能因版本问题出现故障)
  enable-model-protect: true
  #启用粘液材质覆写,使用slimefun-item-model中的材质id覆写已有粘液物品
  enable-slimefun-cmd-override: true
  #启用item-model功能,使用该功能会强加载所有材质包的所有模型
  enable-item-model-override: true
  #启用存储物品解析与展示
  enable-storageitem-display: true
  #启用物品粘液信息显示
  enable-tooltips-display: true

#暂时不能重载这部分功能
hotkeys:
  #复制粘液id的热键
  slimefunid-copy: LEFT_CONTROL,C,BUTTON_1
